global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Reflection;
global using System.Threading.Tasks;
global using System.Text;
global using StambenaZgradaLibrary.Entiteti;
global using StambenaZgradaLibrary.Mapiranje;
global using StambenaZgradaLibrary.DTOs;